SET SCHEMA FN71887;

CREATE TABLE STUDYCLASS(
    ID CHAR(2) NOT NULL,
    CLASSTEACHER VARCHAR(30) NOT NULL,
    STUDENTSLASTNAMES VARCHAR(15) NOT NULL
);


INSERT INTO STUDYCLASS(ID, CLASSTEACHER, STUDENTSLASTNAMES)
VALUES ('1A', 'Elena Mihaleva', 'Popov');
INSERT INTO STUDYCLASS(ID, CLASSTEACHER, STUDENTSLASTNAMES)
VALUES ('1B', 'Nikolai Vitanov', 'Kolchev');
INSERT INTO STUDYCLASS(ID, CLASSTEACHER, STUDENTSLASTNAMES)
VALUES ('2B', 'Ioan Cancov', 'Hadzhiev');
INSERT INTO STUDYCLASS(ID, CLASSTEACHER, STUDENTSLASTNAMES)
VALUES ('2C', 'Dimitar Ivanov', 'Manov');
INSERT INTO STUDYCLASS(ID, CLASSTEACHER, STUDENTSLASTNAMES)
VALUES ('3A', 'Stoyan Petkov', 'Kadreva');
INSERT INTO STUDYCLASS(ID, CLASSTEACHER, STUDENTSLASTNAMES)
VALUES ('3A', 'Stoyan Petkov', 'Kutlarska');
INSERT INTO STUDYCLASS(ID, CLASSTEACHER, STUDENTSLASTNAMES)
VALUES ('3A', 'Stoyan Petkov', 'Mitev');
INSERT INTO STUDYCLASS(ID, CLASSTEACHER, STUDENTSLASTNAMES)
VALUES ('4B', 'Yordan Conev', 'Isheva');
INSERT INTO STUDYCLASS(ID, CLASSTEACHER, STUDENTSLASTNAMES)
VALUES ('4B', 'Dimitar Parushev', 'Durpanova');
INSERT INTO STUDYCLASS(ID, CLASSTEACHER, STUDENTSLASTNAMES)
VALUES ('5A', 'Elena Mihaleva', 'Laleva');
INSERT INTO STUDYCLASS(ID, CLASSTEACHER, STUDENTSLASTNAMES)
VALUES ('5A', 'Elena Mihaleva', 'Gurova');
INSERT INTO STUDYCLASS(ID, CLASSTEACHER, STUDENTSLASTNAMES)
VALUES ('1B', 'Nikolai Vitanov', 'Tumbeva');
INSERT INTO STUDYCLASS(ID, CLASSTEACHER, STUDENTSLASTNAMES)
VALUES ('1B', 'Nikolai Vitanov', 'Gurkova');
INSERT INTO STUDYCLASS(ID, CLASSTEACHER, STUDENTSLASTNAMES)
VALUES ('1A', 'Elena Mihaleva', 'Samardzhiev');
INSERT INTO STUDYCLASS(ID, CLASSTEACHER, STUDENTSLASTNAMES)
VALUES ('1A', 'Elena Mihaleva', 'Dilov');
INSERT INTO STUDYCLASS(ID, CLASSTEACHER, STUDENTSLASTNAMES)
VALUES ('1A', 'Elena Mihaleva', 'Bairakova');
INSERT INTO STUDYCLASS(ID, CLASSTEACHER, STUDENTSLASTNAMES)
VALUES ('1A', 'Elena Mihaleva', 'Burdarska');

ALTER TABLE STUDYCLASS
ADD CONSTRAINT PK_STUDYCLASS PRIMARY KEY (STUDENTSLASTNAMES);

CREATE TABLE STUDENT(
    FIRSTNAME VARCHAR(15) NOT NULL ,
    LASTNAME VARCHAR(15) NOT NULL ,
    AVERAGESUCCESS DECIMAL(3, 2) NOT NULL
);

INSERT INTO STUDENT(FIRSTNAME, LASTNAME, AVERAGESUCCESS)
VALUES ('Ivan', 'Mitev', 3.75);
INSERT INTO STUDENT(FIRSTNAME, LASTNAME, AVERAGESUCCESS)
VALUES ('Gabriela', 'Kadreva', 6.00);
INSERT INTO STUDENT(FIRSTNAME, LASTNAME, AVERAGESUCCESS)
VALUES ('Kamelia', 'Kutlarska', 4.40);
INSERT INTO STUDENT(FIRSTNAME, LASTNAME, AVERAGESUCCESS)
VALUES ('Dragan', 'Hadzhiev', 3.75);
INSERT INTO STUDENT(FIRSTNAME, LASTNAME, AVERAGESUCCESS)
VALUES ('Kostadin', 'Kolchev', 4.75);
INSERT INTO STUDENT(FIRSTNAME, LASTNAME, AVERAGESUCCESS)
VALUES ('Dimitar', 'Popov', 3.75);
INSERT INTO STUDENT(FIRSTNAME, LASTNAME, AVERAGESUCCESS)
VALUES ('Cvetelina', 'Isheva', 3.75);
INSERT INTO STUDENT(FIRSTNAME, LASTNAME, AVERAGESUCCESS)
VALUES ('Elena', 'Durpanova', 3.75);
INSERT INTO STUDENT(FIRSTNAME, LASTNAME, AVERAGESUCCESS)
VALUES ('Mariana', 'Gurova', 3.75);
INSERT INTO STUDENT(FIRSTNAME, LASTNAME, AVERAGESUCCESS)
VALUES ('Elena', 'Laleva', 4.06);
INSERT INTO STUDENT(FIRSTNAME, LASTNAME, AVERAGESUCCESS)
VALUES ('Elena', 'Tumbeva', 5.07);
INSERT INTO STUDENT(FIRSTNAME, LASTNAME, AVERAGESUCCESS)
VALUES ('Elena', 'Gurkova', 2.75);
INSERT INTO STUDENT(FIRSTNAME, LASTNAME, AVERAGESUCCESS)
VALUES ('Ivan', 'Samardzhiev', 3.60);
INSERT INTO STUDENT(FIRSTNAME, LASTNAME, AVERAGESUCCESS)
VALUES ('Lyuben', 'Dilov', 4.80);
INSERT INTO STUDENT(FIRSTNAME, LASTNAME, AVERAGESUCCESS)
VALUES ('Elena', 'Bairakova', 5.00);
INSERT INTO STUDENT(FIRSTNAME, LASTNAME, AVERAGESUCCESS)
VALUES ('Elena', 'Burdarska', 3.95);
INSERT INTO STUDENT(FIRSTNAME, LASTNAME, AVERAGESUCCESS)
VALUES ('Martin', 'Manov', 5.70);

ALTER TABLE STUDENT
ADD CONSTRAINT FK_STUDENT_TO_STUDYCLASS FOREIGN KEY (LASTNAME) REFERENCES STUDYCLASS(STUDENTSLASTNAMES);

--1.	Извеждане на паралелки (идентификатор, ръководител на паралелката, брой ученици)
SELECT ID, CLASSTEACHER,  COUNT(*) AS NUM_STUDENTS
FROM STUDYCLASS, STUDENT
WHERE STUDYCLASS.STUDENTSLASTNAMES = STUDENT.LASTNAME
GROUP BY CLASSTEACHER, ID;

--2.	Извеждане на среден успех на всяка паралелка
SELECT ID, DECIMAL(AVG(AVERAGESUCCESS), 3, 2) AS AVERAGE_SUCCESS
FROM STUDYCLASS SC JOIN STUDENT ST ON SC.STUDENTSLASTNAMES = ST.LASTNAME
GROUP BY ID;

--3.	Извеждане на учениците в паралелка сортирани по успех
SELECT ID, FIRSTNAME || ' ' || LASTNAME AS STUDENT_NAME, AVERAGESUCCESS
FROM STUDYCLASS SC, STUDENT ST
WHERE SC.STUDENTSLASTNAMES = ST.LASTNAME
ORDER BY ID, DECIMAL(AVERAGESUCCESS, 3, 2) DESC;

--4.	Извеждане на учениците в паралелка сортирани по име
SELECT ID, FIRSTNAME || ' ' || LASTNAME AS STUDENT_NAME
FROM STUDYCLASS SC JOIN STUDENT ST ON SC.STUDENTSLASTNAMES = ST.LASTNAME
ORDER BY ID, (FIRSTNAME || ' ' || LASTNAME);